version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./src:/app
      - node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
volumes:
  node_modules: {}
